# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Hojae Han
baseurl:        ""
url:            "https://navybrain.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Hojae Han
  url:          https://navybrain.github.io/
  email:        ghwo812@gmail.com  
  github:       navybrain
  twitter:      

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/navybrain/navybrain.github.io
